name: store_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #   Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.2
  flutter_svg: ^2.3.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # Networking
  dio: ^5.9.1
  dio_cookie_manager: ^3.3.0
  pretty_dio_logger: ^1.4.0
  talker_dio_logger: ^5.1.13

  # Local Storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.5.0

  # Functional Programming
  dartz: ^0.10.1

  # UI Feedback
  fluttertoast: ^9.1.0
  ansicolor: ^2.0.3
  flutter_hooks: ^0.21.3+1
  pin_code_fields: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  injectable_generator: ^2.7.0
  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#004182"
  image: assets/images/splash.png
  fullscreen: true

  android: true
  ios: true
  web: false

  android_12:
    color: "#004182"
    image: assets/images/splash12.png
    icon_background_color: "#004182"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/app_icon.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600